### ISSUE TITLE
Example script fails "on-create.sh" - bash cannot found miniconda

### ISSUE THREAD

**Issue by sandeepksaini** [aws-samples/amazon-sagemaker-notebook-instance-lifecycle-config-samples#31]
Same issue with "on-create.sh " not able to find miniconda and fails.

**Comment by sandeepksaini** [comment]
This issue can be resolved by using :
1) 'EOF' -> Putting quotes at the start will help escape the "$" inside the bash script which will result in the proper variable name used inside this script.
2) \EOF 

After modifications script looks like this:
---------------
#!/bin/bash

set -e

# Use any one of the change to make this script work
#sudo -u ec2-user -i << \EOF
sudo -u ec2-user -i << 'EOF'
unset SUDO_UID
WORKING_DIR=/home/ec2-user/SageMaker/custom-miniconda/
source "$WORKING_DIR/miniconda/bin/activate"
for env in $WORKING_DIR/miniconda/envs/*; do
  BASENAME=$(basename "$env")
  source activate "$BASENAME"
  python -m ipykernel install --user --name "$BASENAME" --display-name "Custom ($BASENAME)"
done
# Optionally, uncomment these lines to disable SageMaker-provided Conda functionality.
# echo "c.EnvironmentKernelSpecManager.use_conda_directly = False" >> /home/ec2-user/.jupyter/jupyter_notebook_config.py
# rm /home/ec2-user/.condarc
EOF

echo "Restarting the Jupyter server.."
restart jupyter-server

**Comment by athewsey** [comment]
I believe this should be resolved by merge of my PR #36, if it's approved

**Comment by mwalczyk** [comment]
Hey I'm still having this issue - is there any word on whether or not it has been fixed? I'm working on Linux and have copy + pasted the scripts verbatim, but I still get the error:

`-bash: line 3: /home/ec2-user/SageMaker/custom-miniconda//miniconda/bin/activate: No such file or directory`

**Comment by mohkar123** [comment]
Yes I am still having the problem above. Same error.` /bin/bash^M: bad interpreter: No such file or directory*.` 
Not sure what to do here.

**Comment by mwalczyk** [comment]
> Yes I am still having the problem above. Same error.` /bin/bash^M: bad interpreter: No such file or directory*.`
> Not sure what to do here. @athewsey

hey @mohkar123 , don't know if this will fix the issue for you, but for me - I had to re-type everything directly into the AWS script "text editor", rather than copy+pasting from Sublime (or whatever text editor you use). Maybe that will work for you too...

**Comment by mohkar123** [comment]
@mwalczyk  Yes that was what worked for me. Actually only the first line /bin/bash I needed to type directly. Everything else, I was able to copy and it ran. Thank you for your help.

**Comment by cvargas-geo** [comment]
Por favor corregir este molesto error por favor /bin/bash^M: bad interpreter: No such file or directory*

**Comment by dmlause** [comment]
Given the above and that this issue hasn't had comments for ~2 years, I am closing this issue. Please open a new issue if needed, thanks.
